name: Full Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  full-tests:
    runs-on: windows-latest
    
    strategy:
      matrix:
        test-type: [contracts, unit, integration, e2e]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run contract tests
      if: matrix.test-type == 'contracts'
      run: npm run test:contracts
      timeout-minutes: 10
    
    - name: Run unit tests
      if: matrix.test-type == 'unit'
      run: npm run test:unit
      timeout-minutes: 15
    
    - name: Run integration tests
      if: matrix.test-type == 'integration'
      run: npm run test:integration
      timeout-minutes: 20
    
    - name: Run E2E tests
      if: matrix.test-type == 'e2e'
      run: npm run test:e2e
      timeout-minutes: 30
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.test-type }}-test-results
        path: test-results/
        retention-days: 30
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.test-type }}-coverage
        path: coverage/
        retention-days: 30

  test-summary:
    runs-on: windows-latest
    needs: full-tests
    if: always()
    
    steps:
    - name: Download all test results
      uses: actions/download-artifact@v4
      with:
        path: test-results/
    
    - name: Generate test summary
      run: |
        echo "# Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Test Type | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Contracts | ${{ needs.full-tests.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Unit | ${{ needs.full-tests.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Integration | ${{ needs.full-tests.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| E2E | ${{ needs.full-tests.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
